# Generated by Django 2.2.3 on 2019-09-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historial',
            fields=[
                ('PEDIDO_NUMBER', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('NOMBRE_PRODUCTO', models.CharField(max_length=100)),
                ('DESCRIPCION_DEL_PRODUCTO', models.CharField(max_length=100)),
                ('ANIO', models.CharField(max_length=100)),
                ('MES', models.CharField(max_length=100)),
                ('DIA', models.CharField(max_length=100)),
                ('HORA', models.CharField(max_length=100)),
                ('PEDIDOS_POR_MES', models.CharField(max_length=100)),
                ('GANANCIA_POR_PLATO', models.CharField(max_length=100)),
            ],
        ),
    ]
