# Generated by Django 2.2.3 on 2019-08-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsCombo', models.BooleanField()),
                ('Combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Combo')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Producto')),
            ],
        ),
    ]
