# Generated by Django 2.2.3 on 2019-09-01 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190818_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
